feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /orcd/scratch/bcs/001/sensein/sails/gesture_data/3d_keypoints/prepared_fmf/mediapipe/SAILS_finetune.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True          # if overfitting / unstable, set False
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: /orcd/scratch/bcs/001/sensein/sails/gesture_data/3d_keypoints/prepared_fmf/mediapipe/SAILS_finetune.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

model: model.skefreqmixformer.Model
model_args:
  num_class: 9              # or 8 if you drop a class + remap labels
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

weight_decay: 0.0005
base_lr: 0.01
step: [15, 30, 45]
warm_up_epoch: 2

device: [0]
batch_size: 64
test_batch_size: 128
num_epoch: 60
nesterov: True